// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDXbzxOUp2U3D0LUSkLJsJFIpWOSWLuSyI",
      authDomain: "metronom-ecommerce-prod.firebaseapp.com",
      projectId: "metronom-ecommerce-prod",
      storageBucket: "metronom-ecommerce-prod.appspot.com",
      messagingSenderId: "837308985609",
      appId: "1:837308985609:web:15b92e8ec1e1568ffc63d8",
      measurementId: "G-VP8PKJNFLN");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW1nzfYG3-MgNbFexXHuMMSzDeuRyv514',
    appId: '1:118312898892:android:5ce68a53d70f72e7303fe9',
    messagingSenderId: '118312898892',
    projectId: 'metronom-ecommerce-stg',
    storageBucket: 'metronom-ecommerce-stg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgTGLviHOGYlPqxOrIlUbf_rsqq9efrnE',
    appId: '1:118312898892:ios:ecf9061ff99cc522303fe9',
    messagingSenderId: '118312898892',
    projectId: 'metronom-ecommerce-stg',
    storageBucket: 'metronom-ecommerce-stg.appspot.com',
    iosClientId:
        '118312898892-c1iltcq6fm88606k26mmufev6p0tevrg.apps.googleusercontent.com',
    iosBundleId: 'com.example.beybicoAdmin',
  );
}
